### ISSUE TITLE
some fonts are only selected on double click

### ISSUE THREAD

**Issue by doczoidberg** [zefoy/ngx-font-picker#16] opened 2019-03-04 11:47 UTC
some fonts are only selected if they are clicked twice.

**Comment by sconix** [comment] 2019-03-04 13:11
I have not seen this, can you tell me how to replicate this in the example app? I.e. what fonts needs to be clicked twice.

**Comment by doczoidberg** [comment] 2019-03-04 13:12
e.g. scroll down to font "quicksand" and click it only once. Text isn't changed.

**Comment by sconix** [comment] 2019-03-04 13:16
Ah it looks like there is some change detection issue. Let me look into this, I will release a fix if the problem is in the library. It could be only in example app or are you seeing this problem in your application code as well?

**Comment by doczoidberg** [comment] 2019-03-04 13:16
I have the same issue in my application

**Comment by sconix** [comment] 2019-03-04 13:19
Ok, thanks for reporting this I will try to get fix out already today.

**Comment by sconix** [comment] 2019-03-05 09:13
This should be fixed in the 7.4.0, but the fix does not make a lot sense that why its needed. So I suspect that this is some sort of Angular bug as well, but let me know if the latest version did not fix this for you.

**Closed** 2019-03-05 09:12 UTC
Labels: bug

**Comment by doczoidberg** [comment] 2019-03-05 10:37
works now. thank you for the fix!
